delete from order_item;
delete from _order;
delete from product;
INSERT INTO PRODUCT (ID,DESCRIPTION,PRICE) VALUES ('A1','Pen Special',20.32);
INSERT INTO PRODUCT (ID,DESCRIPTION,PRICE) VALUES ('A2','Notepad',30.12);
INSERT INTO PRODUCT (ID,DESCRIPTION,PRICE) VALUES ('A3','Eraser',25.23);
INSERT INTO _ORDER (ID,BUYER_EMAIL,CREATION_DATE,TOTAL) VALUES (1,'marcelo@gmail.com','2020-03-25 11:35:49.324',156.25);
INSERT INTO ORDER_ITEM (ID,AMOUNT,PRICE,PRODUCT_ID,ORDER_ID) VALUES (1,1,20.32,'A1',1);
INSERT INTO ORDER_ITEM (ID,AMOUNT,PRICE,PRODUCT_ID,ORDER_ID) VALUES (2,2,30.12,'A2',1);
INSERT INTO ORDER_ITEM (ID,AMOUNT,PRICE,PRODUCT_ID,ORDER_ID) VALUES (3,3,25.23,'A3',1);

